# Generated by Django 5.0.1 on 2024-01-18 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autorite',
            fields=[
                ('id_autorite', models.AutoField(primary_key=True, serialize=False)),
                ('nom_autorite', models.CharField(max_length=255)),
                ('adresse_autorite', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'autorite',
            },
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id_four', models.AutoField(primary_key=True, serialize=False)),
                ('nom_four', models.CharField(max_length=255)),
                ('adresse_four', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'fournisseur',
            },
        ),
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id_marche', models.AutoField(primary_key=True, serialize=False)),
                ('ppm', models.CharField(blank=True, choices=[('PPM-2019', 'PPM-2019'), ('PPM-2020', 'PPM-2020'), ('PPM2021', 'PPM2021'), ('PPM2022', 'PPM2022')], max_length=10, null=True)),
                ('inscription_ppm', models.BooleanField(null=True)),
                ('ac', models.CharField(blank=True, max_length=255, null=True)),
                ('ref_activite', models.CharField(blank=True, max_length=255, null=True)),
                ('type_activite', models.CharField(blank=True, choices=[('T', ' Travaux'), ('F', ' Fournitures'), ('S', ' Services'), ('PI', ' Prestations Intellectuelles')], max_length=255)),
                ('mode', models.CharField(blank=True, choices=[('SQC', 'Sélection sur la Qualité du Consultant'), ('SBQC', 'Sélection sur la Base de qualité et Cout'), ('SBD', 'Sélection sur la Base de Document'), ('SMC', 'Sélection du Moindre Cout'), ('AON', "Appel d'Offre National"), ('AOI', "Appel d'Offre International"), ('AOR', "Appel d'Offre national Restreint"), ('AORI', "Appel d'Offre Restreint International"), ('ED', 'En Mode Direct')], max_length=255, null=True)),
                ('date_prev_lancement_activite', models.DateField(blank=True, null=True)),
                ('date_prev_de_reception', models.DateField(blank=True, null=True)),
                ('budget_prev', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('devise', models.CharField(choices=[('MRU', 'MRU'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=3)),
                ('source_de_financement', models.CharField(choices=[('B.E', "Budget de l'Etat"), ('B.F', 'Bayeur de Fond ou Budget Externe'), ('B.E/B.F', 'Projet financé en deux Partie Etat et B.F')], max_length=100)),
                ('lib_source_de_financement', models.CharField(blank=True, max_length=255, null=True)),
                ('date_publication_activite', models.DateField(blank=True, null=True)),
                ('niveau_suivi', models.CharField(choices=[('AC', 'Autorité Contractante'), ('CPMP', 'Commission de Passation des Marchés Publics'), ('CNCMP', 'Commission Nationale de Contrôle des Marchés Publics'), ('ARMP', 'Autorité de Régulation des Marchés Publics'), ('ANO-B.F', 'Avis de Non Objection du Bayeur de Fond')], max_length=255, null=True)),
                ('etape', models.CharField(choices=[('AMI', "Avis de Manifestation d'Intérêt"), ('DP', 'Demande de Proposition'), ('ET', 'Etude Technique'), ('EF', 'Etude Financière'), ('PM', 'Projet de Marché'), ('Marché', 'Marché attribué'), ('DAO', "Dossier d'Appel d'Offre"), ('PE', "Phase d'Evaluation")], max_length=255, null=True)),
                ('approbation', models.CharField(blank=True, choices=[('NA', 'Non approuvé'), ('Reporté', 'Reporté'), ('ASR', 'Approuvé sous réserve'), ('Approuvé', 'Approuvé'), ('MA', 'Marché attribué')], max_length=255, null=True)),
                ('date_attribution', models.DateField(blank=True, null=True)),
                ('attributaire', models.CharField(blank=True, max_length=255, null=True)),
                ('montant_total_du_marche', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_signature_ac', models.DateField(blank=True, null=True)),
                ('num_marche', models.CharField(blank=True, max_length=255, null=True)),
                ('date_numerotation', models.DateField(blank=True, null=True)),
                ('date_notification', models.DateField(blank=True, null=True)),
                ('delai_execution_en_jour', models.IntegerField(blank=True, null=True)),
                ('date_de_reception', models.DateField(blank=True, null=True)),
                ('retard_constate_en_jour', models.IntegerField(blank=True, null=True)),
                ('etat_du_marche', models.CharField(blank=True, choices=[('PA', 'Projet Marché'), ('MECE', "Marché En cours d'Exécution"), ('MER', 'Marché En Retard'), ('AAN', 'Activité Annulée'), ('MR', 'Marché Resilié'), ('MREC', 'Marché Réceptionné')], max_length=255, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'marche',
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id_contrat', models.AutoField(primary_key=True, serialize=False)),
                ('duree', models.IntegerField(blank=True, null=True)),
                ('conditions', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('id_four', models.ForeignKey(db_column='id_four', on_delete=django.db.models.deletion.CASCADE, to='public_market.fournisseur')),
                ('id_marche', models.ForeignKey(db_column='id_marche', on_delete=django.db.models.deletion.CASCADE, to='public_market.marche')),
            ],
            options={
                'db_table': 'contrat',
            },
        ),
        migrations.CreateModel(
            name='Piecedetachee',
            fields=[
                ('id_piece', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_ajout', models.DateTimeField()),
                ('id_marche', models.ForeignKey(db_column='id_marche', on_delete=django.db.models.deletion.CASCADE, to='public_market.marche')),
            ],
            options={
                'db_table': 'piecedetachee',
            },
        ),
        migrations.CreateModel(
            name='Ppm',
            fields=[
                ('id_ppm', models.AutoField(primary_key=True, serialize=False)),
                ('annee_ppm', models.IntegerField()),
                ('id_autorite', models.ForeignKey(db_column='id_autorite', on_delete=django.db.models.deletion.CASCADE, to='public_market.autorite')),
            ],
            options={
                'db_table': 'ppm',
            },
        ),
        migrations.AddField(
            model_name='marche',
            name='id_ppm',
            field=models.ForeignKey(db_column='id_ppm', on_delete=django.db.models.deletion.CASCADE, to='public_market.ppm'),
        ),
        migrations.CreateModel(
            name='Soumission',
            fields=[
                ('id_soum', models.AutoField(primary_key=True, serialize=False)),
                ('date_soumission', models.DateField(blank=True, null=True)),
                ('montant', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_four', models.ForeignKey(db_column='id_four', on_delete=django.db.models.deletion.CASCADE, to='public_market.fournisseur')),
                ('id_marche', models.ForeignKey(db_column='id_marche', on_delete=django.db.models.deletion.CASCADE, to='public_market.marche')),
            ],
            options={
                'db_table': 'soumission',
            },
        ),
    ]
